In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.svm   import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix, classification_report
from scipy import sparse
from google.colab import drive
drive.mount('/content/drive')
#drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


In [3]:
#dataset = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/Data/SumukhDataCollection/ML_data_new.csv')
dataset = pd.read_csv('/content/drive/My Drive/ColabNotebooks/Data/2023_300Trials_InstantPressAndRelease/Features_All.csv')
#dataset = pd.read_csv("/content/drive/MyDrive/ColabNotebooks/Data/SumukhDataCollection/ML_data_new.csv", usecols=['MEAN8','STD_DEV8','SKEW8','KURTOSIS8','STD_ERROR8','MEAN_FREQ8','MED_FREQ8','Label'])
dataset.shape

(1503, 57)

In [4]:
X = dataset.loc[:,(dataset.columns != 'Label')]
X.head()


MEAN1  STD_DEV1     SKEW1  KURTOSIS1  STD_ERROR1  MEAN_FREQ1  MED_FREQ1  \
0  1.745318  2.465114  0.033822   7.106584    0.106776   50.916342  51.367188   
1  2.308411  3.166170 -0.414113   6.065673    0.216942   51.861420  52.929688   
2  2.554007  3.533496  0.725908   9.029324    0.208940   51.602053  52.734375   
3  2.477679  3.622225  0.029426   7.417754    0.242562   50.124160  49.804688   
4  2.263393  3.097709  0.326364   5.931556    0.207438   51.016363  51.757812   

      MEAN2  STD_DEV2     SKEW2  ...  STD_ERROR7  MEAN_FREQ7  MED_FREQ7  \
0  5.544944  7.575255 -0.720034  ...    0.115597   51.417373  52.343750   
1  7.028037  9.938553 -0.301084  ...    0.190825   50.850650  51.562500   
2  6.515679  9.239693  0.096353  ...    0.146443   49.890265  50.195312   
3  5.075893  8.814023 -0.347195  ...    0.235679   51.886866  52.929688   
4  5.410714  7.867830 -1.426058  ...    0.238147   51.045120  52.148438   

      MEAN8  STD_DEV8     SKEW8  KURTOSIS8  STD_ERROR8  MEAN_FREQ8  MED_FREQ8  
0  1.243446  1.720663  0.508245   9.214567    0.074530   51.025038  51.953125  
1  1.401869  2.290482 -1.103772  13.738547    0.156941   51.528474  53.906250  
2  1.407666  2.016353  0.803876   8.864138    0.119229   49.999292  50.000000  
3  1.352679  1.900585  1.354450  13.039627    0.127273   48.613781  47.851562  
4  1.366071  1.829464  0.356279   5.305755    0.122510   50.330548  50.390625  

[5 rows x 56 columns]

In [5]:
y = dataset[["Label"]]
y.head()

Label
0      1
1      1
2      1
3      1
4      1

In [6]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y = label_encoder.fit_transform(y)

y_dataframe = pd.DataFrame(y, columns=['Label'])

y_dataframe.head()

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Label
0      0
1      0
2      0
3      0
4      0

In [7]:
dataset.dtypes

MEAN1         float64
STD_DEV1      float64
SKEW1         float64
KURTOSIS1     float64
STD_ERROR1    float64
MEAN_FREQ1    float64
MED_FREQ1     float64
MEAN2         float64
STD_DEV2      float64
SKEW2         float64
KURTOSIS2     float64
STD_ERROR2    float64
MEAN_FREQ2    float64
MED_FREQ2     float64
MEAN3         float64
STD_DEV3      float64
SKEW3         float64
KURTOSIS3     float64
STD_ERROR3    float64
MEAN_FREQ3    float64
MED_FREQ3     float64
MEAN4         float64
STD_DEV4      float64
SKEW4         float64
KURTOSIS4     float64
STD_ERROR4    float64
MEAN_FREQ4    float64
MED_FREQ4     float64
MEAN5         float64
STD_DEV5      float64
SKEW5         float64
KURTOSIS5     float64
STD_ERROR5    float64
MEAN_FREQ5    float64
MED_FREQ5     float64
MEAN6         float64
STD_DEV6      float64
SKEW6         float64
KURTOSIS6     float64
STD_ERROR6    float64
MEAN_FREQ6    float64
MED_FREQ6     float64
MEAN7         float64
STD_DEV7      float64
SKEW7         float64
KURTOSIS7 

In [90]:
y_dataframe['Label'].value_counts()

0    280
1    280
2    280
3    280
4    280
Name: Label, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn import svm


In [9]:
X_train, X_remaining, y_train, y_remaining = train_test_split(X, y_dataframe, test_size=0.3, random_state=42)

X_test, X_val, y_test, y_val = train_test_split(X_remaining, y_remaining, test_size=0.333, random_state=42)

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)
print("X_val shape:", X_val.shape)
print("y_val shape:", y_val.shape)

X_train shape: (1052, 56)
y_train shape: (1052, 1)
X_test shape: (300, 56)
y_test shape: (300, 1)
X_val shape: (151, 56)
y_val shape: (151, 1)


#SVM

In [10]:
svm_classifier = svm.SVC(kernel='linear')

svm_classifier.fit(X_train, y_train)

accuracy = svm_classifier.score(X_test, y_test)

#print(f'Testing Accuracy: {accuracy}')

y_pred = svm_classifier.predict(X_train)
print('Train Accuracy\t=' + str(accuracy_score(y_train, y_pred)*100))
y_pred = svm_classifier.predict(X_val)
print('Validation Accuracy' + str(accuracy_score(y_val, y_pred)*100))
y_pred = svm_classifier.predict(X_test)
print('Test Accuracy\t=' + str(accuracy_score(y_test, y_pred)*100))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Accuracy	=42.20532319391635
Validation Accuracy27.81456953642384
Test Accuracy	=26.333333333333332


In [11]:
y_pred= svm_classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
classes = ["C", "D", "E", "F", "G"]
print(cm)
# Plot confusion matrix
plt.figure(figsize=(8, 6))

# plt.imshow(cm, interpolation='nearest', cmap=plt.cm.binary)
# plt.title('Confusion Matrix')
# plt.colorbar()
# tick_marks = np.arange(len(classes))
# plt.xticks(tick_marks, classes)
# plt.yticks(tick_marks, classes)
# plt.xlabel('Predicted Label')
# plt.ylabel('True Label')

# for i in range(len(classes)):
#     for j in range(len(classes)):
#         plt.text(j, i, cm[i, j], ha='center', va='center', color='red')

# plt.show()

[[20 14  7  3 10]
 [32  9 19  0  7]
 [10  8 15  5  9]
 [ 7  6 16 16 27]
 [18  7  6 10 19]]


<Figure size 800x600 with 0 Axes>

<Figure size 800x600 with 0 Axes>

In [12]:
from sklearn.model_selection import cross_val_score, cross_val_predict
svm_classifier.random_state = 0
scores = cross_val_score(svm_classifier, X, y_dataframe, cv=10)
print('CROSS VALIDATION \n Mean={} Std {} \n scores {}'.format(np.mean(scores),np.std(scores), scores))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

CROSS VALIDATION 
 Mean=0.25672847682119204 Std 0.06450413155062981 
 scores [0.31788079 0.34437086 0.24503311 0.14       0.34       0.24666667
 0.20666667 0.21333333 0.30666667 0.20666667]


In [65]:
print(classification_report(y_test, y_pred, target_names=classes,digits=4))

              precision    recall  f1-score   support

           C     0.3175    0.3704    0.3419        54
           D     0.3171    0.2097    0.2524        62
           E     0.2714    0.3878    0.3193        49
           F     0.4634    0.3167    0.3762        60
           G     0.6154    0.7273    0.6667        55

    accuracy                         0.3964       280
   macro avg     0.3970    0.4023    0.3913       280
weighted avg     0.3991    0.3964    0.3893       280



#Random Forest

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.model_selection import train_test_split

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [20]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)
X_test = sc.transform(X_test)

numberofclasses =len(set(y_dataframe['Label']))
print(numberofclasses)
lda = LDA(n_components=numberofclasses-1)
X_trainlda = lda.fit_transform(X_train, y_train)
#print('#class={} {} {}'.format(len(fingers), X_train.shape, X_trainlda.shape))
X_test = lda.transform(X_test)
X_val = lda.transform(X_val)


classifier = RandomForestClassifier(max_depth=6, n_estimators=20, random_state=0)
classifier.fit(X_trainlda, y_train)
print('**********************************')
y_pred = classifier.predict(X_trainlda)
print('Train Accuracy\t=' + str(accuracy_score(y_train, y_pred)*100))
y_pred = classifier.predict(X_val)
print('Validation Accuracy' + str(accuracy_score(y_val, y_pred)*100))
y_pred = classifier.predict(X_test)
print('Test Accuracy\t=' + str(accuracy_score(y_test, y_pred)*100))
print('**********************************')
print('Classes Predicted {}'.format(set(y_test['Label'])))
print(confusion_matrix(y_test, y_pred))

from sklearn.model_selection import cross_val_score, cross_val_predict
classifier.random_state = 0
scores = cross_val_score(classifier, X, y_dataframe, cv=10)
print('CROSS VALIDATION \n Mean={} Std {} \n scores {}'.format(np.mean(scores),np.std(scores), scores))

5
**********************************
Train Accuracy	=56.55893536121673
Validation Accuracy30.4635761589404
Test Accuracy	=28.333333333333332
**********************************
Classes Predicted {0, 1, 2, 3, 4}
[[22 11  8  3 10]
 [21 14 22  1  9]
 [11  5 17  8  6]
 [ 6  7 23 13 23]
 [ 9  5 14 13 19]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
<ipython-input-20-3eaf87d4d686>:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(X_trainlda, y_train)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for examp

CROSS VALIDATION 
 Mean=0.25607505518763796 Std 0.09396722105504932 
 scores [0.33112583 0.36423841 0.19205298 0.14       0.38666667 0.35333333
 0.16666667 0.12       0.26666667 0.24      ]


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
